import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://lgihe.ac.ug';
  
  // Static pages
  const routes = [
    '',
    '/about',
    '/about/history',
    '/about/mission',
    '/about/principal',
    '/about/board',
    '/privacy',
    '/privacy/preferences',
    '/academics',
    '/academics/undergraduate',
    '/academics/diploma',
    '/academics/certificate',
    '/academics/postgraduate',
    '/academics/programmes',
    '/academics/schools',
    '/academics/schools/education',
    '/academics/schools/arts',
    '/academics/schools/science',
    '/academics/schools/business',
    '/admissions',
    '/admissions/how-to-apply',
    '/admissions/requirements',
    '/admissions/fees',
    '/admissions/dates',
    '/admissions/portal',
    '/admissions/undergraduate',
    '/admissions/diploma',
    '/admissions/certificate',
    '/admissions/postgraduate',
    '/student-life',
    '/student-life/campus',
    '/student-life/library',
    '/student-life/health',
    '/student-life/support',
    '/student-life/events',
    '/student-life/union',
    '/student-life/portal',
    '/research',
    '/research/projects',
    '/research/publications',
    '/staff',
    '/staff/academic',
    '/staff/administrative',
    '/staff/team',
    '/resources',
    '/resources/downloads',
    '/resources/policies',
    '/resources/media',
    '/news',
    '/events',
    '/contact',
    '/jobs',
    '/tenders',
    '/opportunities',
  ].map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: route === '' ? 1 : route.split('/').length === 2 ? 0.8 : 0.6,
  }));

  return routes;
}
